# Generated by Django 5.1.5 on 2025-11-07 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_visitormessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='subject',
        ),
    ]
