# Generated by Django 5.1.5 on 2025-11-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_chat_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='read_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
