# Generated by Django 5.1.5 on 2026-02-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_chat_read_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolfeestructure',
            name='components',
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='schoolfeestructure',
            name='class_room',
        ),
        migrations.RemoveField(
            model_name='schoolfeestructure',
            name='session',
        ),
        migrations.AlterField(
            model_name='session',
            name='year',
            field=models.IntegerField(default=2026),
        ),
        migrations.DeleteModel(
            name='FeeComponent',
        ),
        migrations.DeleteModel(
            name='FeePayment',
        ),
        migrations.DeleteModel(
            name='SchoolFeeStructure',
        ),
    ]
